# ================================================================================
# Random suffix for Key Vault name
# --------------------------------------------------------------------------------
# Generates a random string used to ensure the Key Vault name is globally
# unique. Azure Key Vault names must be unique across all Azure tenants.
#
# Notes
# - Only lowercase alphanumeric characters are used.
# - Special characters are disabled for DNS compatibility.
# ================================================================================
resource "random_string" "key_vault_suffix" {
  length  = 8
  special = false
  upper   = false
}

# ================================================================================
# Azure Key Vault
# --------------------------------------------------------------------------------
# Creates the centralized Key Vault used to store credentials and secrets
# generated by the deployment.
#
# Notes
# - RBAC authorization is enabled instead of access policies.
# - The Key Vault name includes a random suffix for global uniqueness.
# - Purge protection is disabled to simplify teardown during testing.
# ================================================================================
resource "azurerm_key_vault" "credentials_key_vault" {
  name                = "creds-kv-${random_string.key_vault_suffix.result}"
  resource_group_name = azurerm_resource_group.project_rg.name
  location            = var.project_location

  sku_name  = "standard"
  tenant_id = data.azurerm_client_config.current.tenant_id

  purge_protection_enabled   = false
  rbac_authorization_enabled = true
}

# ================================================================================
# Key Vault RBAC role assignment
# --------------------------------------------------------------------------------
# Grants the current user or service principal permission to manage
# secrets within the Key Vault.
#
# Role
# - Key Vault Secrets Officer
# ================================================================================
resource "azurerm_role_assignment" "kv_role_assignment" {
  scope                = azurerm_key_vault.credentials_key_vault.id
  role_definition_name = "Key Vault Secrets Officer"
  principal_id         = data.azurerm_client_config.current.object_id
}

# ================================================================================
# Random password for Linux VM
# --------------------------------------------------------------------------------
# Generates a strong password used for the Linux VM administrator account.
#
# Notes
# - Password length is set to 24 characters.
# - Special characters are disabled to avoid compatibility issues
#   with certain automation scripts.
# ================================================================================
resource "random_password" "vm_password" {
  length  = 24
  special = false
}

# ================================================================================
# Linux VM credentials secret
# --------------------------------------------------------------------------------
# Stores the Linux VM administrator credentials in Azure Key Vault as
# a JSON secret.
#
# Secret format
# {
#   "username": "sysadmin",
#   "password": "<generated password>"
# }
# ================================================================================
resource "azurerm_key_vault_secret" "linux_vm_secret" {
  name = "vm-credentials"

  value = jsonencode({
    username = "sysadmin"
    password = random_password.vm_password.result
  })

  key_vault_id = azurerm_key_vault.credentials_key_vault.id

  content_type = "application/json"

  depends_on = [
    azurerm_role_assignment.kv_role_assignment
  ]
}